name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile and Run Tests
      working-directory: tests
      run: |
        g++ -I../include ini.cpp && ./a.out
        
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    - name: Setup CL
      shell: cmd
      run: |
        @echo off
        setlocal EnableDelayedExpansion

        set "vswhere=%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
        set "install_path="

        for /f "usebackq tokens=*" %%i in (`"!vswhere!" -latest -prerelease -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
            set "install_path=%%i"
        )

        if defined install_path (
            echo Setting up compile environment...
            call "!install_path!\VC\Auxiliary\Build\vcvarsall.bat" x64
        ) else (
            echo Error: MSVC build tools not found.
            echo Please install Visual Studio Community
            exit /b 1
        )

    - name: Compile and Run Tests on Windows
      working-directory: tests
      shell: cmd
      run: |
        cl /EHsc /I..\include ini.cpp
    - run: ini.exe
      working-directory: tests
